name: Melde ein Problem mit HomematicIP (local)
description: Melde ein Problem mit HomematicIP (local)
body:
  - type: markdown
    attributes:
      value: |
        Dieses Formular dient ausschließlich zur Meldung von Fehlern! Nutze die Diskussionen für Funktions- und Support-Anfragen.
        Bitte vermeide unnötigen Aufwand, indem die folgenden Punkte aufmerksam gelesen werden. Andernfalls behalte ich mir das Recht vor, das Issue kommentarlos zu schließen.
  - type: checkboxes
    attributes:
      label: Ich stimme dem Folgenden zu
      options:
        - label: Ich habe die [Dokumentation](https://github.com/sukramj/homematicip_local#homematicip_local) gelesen
          required: true
        - label: Ich habe die [Fehlerbehebung-Dokumentation](docs/homeassistant_troubleshooting.md) gelesen, und versucht das Problem selbstständig zu identifizieren/beheben.
          required: true
        - label: Ich habe die [FAQs](https://github.com/sukramj/homematicip_local#frequently-asked-questions) gelesen
          required: true
        - label: Ich kenne die neuesten [Versionshinweise](https://github.com/sukramj/homematicip_local/releases)
          required: true
        - label: Mir ist klar, dass eine Integration, die über HACS installiert wurde, auch über HACS aktualisiert werden muss
          required: true
        - label: Das Backend (CCU/Homegear/...) funktioniert wie erwartet, Geräte können angelernt werden und sind über deren eigene Benutzeroberfläche steuerbar
          required: true
        - label: Ich verwende die neueste Version der Integration (und von Home Assistant).
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Das Problem
      description: >-
        Beschreiben hier das Problem. Erzähle was Du versucht hast, um das Problem selber zu lösen, und was dabei passiert ist. Zeige ggf. Codebeispiele.

        Beispielcode und Screenshots sind viel besser als lange Texte!
        Beschreibe das Problem klar und eindeutig!
  - type: markdown
    attributes:
      value: |
        ## Systemumgebung
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Bei welcher Version von HomematicIP (lokal) tritt das Problem auf?
      placeholder: 1.8x.x
      description: >
        Zu finden unter: HACS -> Integrationen
  - type: input
    attributes:
      label: Welche war die letzte funktionierende Version von HomematicIP (local)?
      placeholder: 1.8x.x
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Welche Art von Installation verwendest Du?
      description: >
        Zu finden unter: [Einstellungen -> System-> Reparaturen -> Drei Punkte oben rechts -> System information](https://my.home-assistant.io/redirect/system_health/).

        [![Öffnen die Home Assistant-Instanz und zeige Sie Gesundheitsinformationen zu deinem System an.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Welche Art von Installation verwendest Du als Homematic-Backend?
      options:
        - RaspberryMatic Einzeln
        - RaspberryMatic HA-Addon
        - Debmatic
        - CCU3
        - CCU2
        - Homegear
  - type: input
    attributes:
      label: Welche Version des Homematic-Backends verwendest Du?
      placeholder: 3.81.x
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: input
    attributes:
      label: Welche Hardware verwendest Du für das System?
      placeholder: Proxmox, Pi3, Pi4, Pi5
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: checkboxes
    attributes:
      label: Welche Konfigurationsdetails verwendest Du?
      options:
        - label: TLS
          required: false
        - label: Callback Daten ([siehe](https://github.com/sukramj/homematicip_local#callback_host-and-callback_port))
          required: false
  - type: checkboxes
    attributes:
      label: Welche Schnittstellen werden verwendet?
      options:
        - label: Homematic IP
          required: false
        - label: Homematic (Bidcos-RF)
          required: false
        - label: Groups (Heating-Group)
          required: false
        - label: BidCos-Wired (HM-Wired)
          required: false
        - label: CuXD
          required: false
        - label: CCU-Jack
          required: false

  - type: textarea
    attributes:
      label: Diagnoseinformationen (sehr hilfreich!) (keine Protokolle hier)
      placeholder: "Ziehe die Diagnosedatendatei per Drag-and-Drop hierher (kopiere nicht den Inhalt)"
      description: >-
        Diese Integration bieten die Möglichkeit [Diagnosedaten herunterzuladen](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **Es ist sehr hilfreich, wenn Du die Diagnosedaten für das Gerät, mit dem das Probleme besteht, herunterladen und die Datei per <ins>Drag-and-Drop</ins> in das Textfeld unten ziehen könntest.**

        Dadurch können im Allgemeinen Fehler genauer lokalisiert und Probleme schneller gelöst werden.
  - type: textarea
    attributes:
      label: Auszug aus der Protokolldatei (sehr hilfreich). Gibt es in den Protokollen etwas, das nützlich sein könnte? Das Protokoll (Einstellungen/System/Protokolle -> Unveränderte Protokolle laden) ist die beste Quelle zur Fehlerbehebung!
      description: Beispielsweise Fehlermeldungen. Wechsele nicht zum DEBUG, wenn das nicht angefordert wurde.
      render: txt
  - type: textarea
    attributes:
      label: Weitere Informationen
      description: >
        Wenn Du weitere Informationen hast, verwende das Feld unten, z.B. wie das Problem reproduziert werden kann, Screenshots usw.
