name: Melde ein Problem mit Homematic(IP) Local for OpenCCU
description: Melde ein Problem mit Homematic(IP) Local for OpenCCU
body:
  - type: markdown
    attributes:
      value: |
        Dieses Formular dient ausschließlich zur Meldung von Fehlern!
        Bei Fragen zur Installation nutze bitte die entsprechenden Foren, falls die Dokumentation nicht ausreicht.
        Nutze die Diskussionen für Funktions- und sonstige Anfragen.

        ⚠️ **WICHTIG: Sinnvoller Support ist nur möglich, wenn alle erforderlichen Informationen bereitgestellt werden!**
        Dazu gehören insbesondere: **Integrationsdiagnose (.json-Datei)** und **Protokolldatei**.
        Issues ohne diese Informationen können kommentarlos geschlossen werden.

        Bitte vermeide unnötigen Aufwand, indem die folgenden Punkte aufmerksam gelesen werden.
  - type: checkboxes
    attributes:
      label: Ich stimme dem Folgenden zu
      options:
        - label: Ich habe die [Dokumentation](https://github.com/sukramj/homematicip_local#homematicip_local) gelesen
          required: true
        - label: Ich habe die [Fehlerbehebung-Dokumentation](https://github.com/SukramJ/aiohomematic/blob/devel/docs/homeassistant_troubleshooting.md) gelesen, und versucht das Problem selbstständig zu identifizieren/beheben.
          required: true
        - label: Ich habe die [FAQs](https://github.com/sukramj/homematicip_local#frequently-asked-questions) gelesen
          required: true
        - label: Ich habe das [Glossar](https://github.com/SukramJ/aiohomematic/blob/devel/docs/glossary.md) gelesen und verstehe den Unterschied zwischen Integration, Add-on und Backend
          required: true
        - label: Ich kenne die neuesten [Versionshinweise](https://github.com/sukramj/homematicip_local/releases)
          required: true
        - label: Mir ist klar, dass eine Integration, die über HACS installiert wurde, auch über HACS aktualisiert werden muss
          required: true
        - label: Das Backend (CCU/Homegear/...) funktioniert wie erwartet, Geräte können angelernt werden und sind über deren eigene Benutzeroberfläche steuerbar
          required: true
        - label: Ich verwende die neueste Version der Integration (und von Home Assistant).
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Das Problem
      description: >-
        Bitte beantworte die folgenden Fragen:

        1. **Was passiert?** (Beschreibe das tatsächliche Verhalten)

        2. **Wann/Wie tritt es auf?** (Nach Neustart, zu bestimmten Zeiten, bei bestimmten Geräten, ...)

        3. **Was hast Du erwartet?** (Beschreibe das erwartete Verhalten)

        4. **Was hast Du bereits versucht?** (Neustart, Neuladen, Neu-Anlernen, ...)

        Keine Protokolle hier! Screenshots sind willkommen.
  - type: markdown
    attributes:
      value: |
        ## Systemumgebung
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Bei welcher Version von HomematicIP (lokal) tritt das Problem auf?
      placeholder: 2.x.x
      description: >
        Zu finden unter: HACS -> Integrationen
  - type: input
    attributes:
      label: Welche war die letzte funktionierende Version von Homematic(IP) Local for OpenCCU?
      placeholder: 2.x.x
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Welche Art von Installation verwendest Du?
      description: >
        Zu finden unter: [Einstellungen -> System-> Reparaturen -> Drei Punkte oben rechts -> System information](https://my.home-assistant.io/redirect/system_health/).

        [![Öffnen die Home Assistant-Instanz und zeige Sie Gesundheitsinformationen zu deinem System an.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Welche Art von Installation verwendest Du als Homematic-Backend?
      options:
        - OpenCCU Einzeln
        - OpenCCU HA-Addon
        - piVCCU/Debmatic
        - CCU3
        - CCU2
        - Homegear
  - type: input
    attributes:
      label: Welche Version des Homematic-Backends verwendest Du?
      placeholder: 3.85.x
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: input
    attributes:
      label: Welche Hardware verwendest Du für das System?
      placeholder: Proxmox, Pi3, Pi4, Pi5
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: checkboxes
    attributes:
      label: Welche Konfigurationsdetails verwendest Du?
      options:
        - label: TLS
          required: false
        - label: Callback Daten ([siehe](https://github.com/sukramj/homematicip_local#callback_host-and-callback_port))
          required: false
  - type: checkboxes
    attributes:
      label: Welche Schnittstellen werden verwendet?
      options:
        - label: Homematic IP
          required: false
        - label: Homematic (Bidcos-RF)
          required: false
        - label: Groups (Heating-Group)
          required: false
        - label: BidCos-Wired (HM-Wired)
          required: false
        - label: CuXD
          required: false
        - label: CCU-Jack
          required: false

  - type: textarea
    attributes:
      label: Diagnoseinformationen (keine Protokolle hier!)
      placeholder: "Ziehe die .json-Diagnosedatei per Drag-and-Drop hierher. KEINE Log-Inhalte einfügen!"
      description: >-
        ⚠️ **WICHTIG**: Nur die `.json`-Diagnosedatei per Drag-and-Drop hochladen!
        NICHT Log-Inhalte hier einfügen - die gehören in das Log-Feld unten.

        **So erhältst Du Diagnosedaten**: [Einstellungen -> Geräte -> Integration auswählen -> Diagnose herunterladen](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics)

        Überspringe dieses Feld nur, wenn Du ein Problem bei der Erstinstallation meldest.
  - type: textarea
    attributes:
      label: Protokolldatei (am besten DEBUG-Log)
      placeholder: "Ziehe die Protokolldatei per Drag-and-Drop hierher."
      description: >-
        **Empfohlen**: DEBUG-Protokollierung aktivieren, bevor das Problem reproduziert wird!

        **DEBUG aktivieren**: Einstellungen → Geräte → Integration auswählen → Debug-Protokollierung aktivieren

        Dann Problem reproduzieren und herunterladen: Einstellungen → System → Protokolle → Unveränderte Protokolle laden
  - type: textarea
    attributes:
      label: Weitere Informationen
      description: >
        Wenn Du weitere Informationen hast, verwende das Feld unten, z.B. wie das Problem reproduziert werden kann, Screenshots usw.
