name: Report an issue with Homematic(IP) Local for OpenCCU
description: Report an issue with Homematic(IP) Local for OpenCCU
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        For installation support, use the relevant forums if the documentation is insufficient.
        Use the discussions for feature requests and other stuff.

        âš ï¸ **IMPORTANT: Meaningful support is only possible if all required information is provided!**
        This includes in particular: **Integration diagnostics (.json file)** and **log file**.
        Issues without this information may be closed without comment.

        ðŸ“– **[Why are diagnostics and logs so important?](https://github.com/SukramJ/aiohomematic/blob/devel/docs/debug_data_importance.md)** - Please read this to understand what we need and why.

        Please avoid unnecessary effort by reading the points below.
  - type: checkboxes
    attributes:
      label: I agree to the following
      options:
        - label: I have read the [documentation](https://github.com/sukramj/homematicip_local#homematicip_local)
          required: true
        - label: I have read the [troubleshooting documentation](https://github.com/SukramJ/aiohomematic/blob/devel/docs/homeassistant_troubleshooting.md), and tried to identify/solve the issue by myself.
          required: true
        - label: I have read the [FAQs](https://github.com/sukramj/homematicip_local#frequently-asked-questions)
          required: true
        - label: I have read the [Glossary](https://github.com/SukramJ/aiohomematic/blob/devel/docs/glossary.md) and understand the difference between Integration, Add-on, and Backend
          required: true
        - label: I am aware of the latest [release notes](https://github.com/sukramj/homematicip_local/releases)
          required: true
        - label: I am aware that an integration that was installed via HACS also needs to be updated via HACS
          required: true
        - label: The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
          required: true
        - label: I am running the latest version of the custom_component (and Home Assistant)
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Please answer the following questions:

        1. **What is happening?** (Describe the actual behavior)

        2. **When/How does it occur?** (After restart, at specific times, with specific devices, ...)

        3. **What did you expect?** (Describe the expected behavior)

        4. **What have you tried?** (Restart, reload, re-pairing, ...)

        NO logs here!

        ðŸ’¡ **Tip:** For device-related issues (missing entities, wrong values, strange behavior), screenshots are much more helpful than long text descriptions! Show us what you see in Home Assistant or the CCU.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Homematic(IP) Local for OpenCCU has the issue?
      placeholder: 2.x.x
      description: >
        Can be found in: HACS -> Integrations
  - type: input
    attributes:
      label: What was the last working version of Homematic(IP) Local for OpenCCU?
      placeholder: 2.x.x
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings -> System-> Repairs -> Three Dots in Upper Right -> System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show health information about your system.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running for your Homematic backend?
      options:
        - OpenCCU Standalone
        - OpenCCU HA-Addon
        - piVCCU/Debmatic
        - CCU3
        - CCU2
        - Homegear
  - type: input
    attributes:
      label: Which version of your Homematic backend are you running?
      placeholder: 3.85.x
      description: >
        If known, otherwise leave blank.
  - type: input
    attributes:
      label: What hardware are you running for your system?
      placeholder: Proxmox, Pi3, Pi4, Pi5
      description: >
        If known, otherwise leave blank.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: checkboxes
    attributes:
      label: Which config details do you use
      options:
        - label: TLS
          required: false
        - label: callback data ([see](https://github.com/sukramj/homematicip_local#callback_host-and-callback_port))
          required: false
  - type: checkboxes
    attributes:
      label: Which interfaces do you use?
      options:
        - label: Homematic IP
          required: false
        - label: Homematic (Bidcos-RF)
          required: false
        - label: Groups (Heating-Group)
          required: false
        - label: BidCos-Wired (HM-Wired)
          required: false
        - label: CuXD
          required: false
        - label: CCU-Jack
          required: false

  - type: textarea
    attributes:
      label: Diagnostics information (no logs here!)
      placeholder: "Drag-and-drop the .json diagnostics file here. DO NOT paste log content!"
      description: >-
        âš ï¸ **IMPORTANT**: Only upload the `.json` diagnostics file via drag-and-drop!
        Do NOT copy-paste log content here - that belongs in the log field below.

        **How to get diagnostics**: [Settings -> Devices -> Select integration -> Download diagnostics](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics)

        Skip this field only if you report an issue with initial setup/installation.
  - type: textarea
    attributes:
      label: Log file (preferably DEBUG log)
      placeholder: "Drag-and-drop the log file here."
      description: >-
        **Recommended**: Enable DEBUG logging before reproducing the issue!

        **How to enable DEBUG**: Settings â†’ Devices â†’ Select integration â†’ Enable debug logging

        Then reproduce the issue and download: Settings â†’ System â†’ Logs â†’ Load unchanged logs
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below. e.g. how to reproduce the issue, screenshots, ...
