blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/sukramj/hahomematic/discussions
    about: Please use our Discussion Forum for making feature requests.
