"""Tests for the GitHub issue-analyzer helper ``detect_ai_generated_analysis``."""

from __future__ import annotations

import importlib.util
from pathlib import Path
import sys
import types

import pytest

_SCRIPT_PATH = Path(__file__).resolve().parents[2] / ".github" / "scripts" / "analyze_issue.py"


def _load_analyze_issue() -> types.ModuleType:
    """Load the standalone analyzer script with its heavy third-party deps stubbed out."""
    if "anthropic" not in sys.modules:
        anthropic_stub = types.ModuleType("anthropic")
        anthropic_stub.Anthropic = object  # type: ignore[attr-defined]
        sys.modules["anthropic"] = anthropic_stub
    if "github" not in sys.modules:
        github_stub = types.ModuleType("github")
        github_stub.Auth = object  # type: ignore[attr-defined]
        github_stub.Github = object  # type: ignore[attr-defined]
        github_stub.GithubException = type("GithubException", (Exception,), {})  # type: ignore[attr-defined]
        github_stub.Repository = object  # type: ignore[attr-defined]
        sys.modules["github"] = github_stub

    spec = importlib.util.spec_from_file_location("analyze_issue_under_test", _SCRIPT_PATH)
    if spec is None or spec.loader is None:
        pytest.fail(f"Could not load analyzer script from {_SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    # Register before exec so dataclass/typing machinery can resolve the module by name.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


analyze_issue = _load_analyze_issue()


@pytest.mark.parametrize(
    "body",
    [
        "Devices are unavailable after restart. Diagnostics and log attached.",
        "Nach dem Neustart sind die Geräte nicht erreichbar. Diagnose und Log sind angehängt.",
        "It crashes. Here is my log file: https://github.com/user-attachments/files/1/home-assistant.log",
        "",
    ],
)
def test_detect_ai_generated_analysis_clean_report(body: str) -> None:
    """Do not flag a normal report that contains no AI prose."""
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is False
    assert result["strong"] is False
    assert result["markers"] == []


@pytest.mark.parametrize(
    "body",
    [
        "As an AI language model, I analyzed your logs and found a connection issue.",
        "Als KI habe ich deine Logs analysiert und ein Verbindungsproblem gefunden.",
        "This was generated by a large language model based on the diagnostics.",
    ],
)
def test_detect_ai_generated_analysis_strong_marker(body: str) -> None:
    """Flag a single explicit self-identification marker as a strong detection."""
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is True
    assert result["strong"] is True
    assert result["markers"]


def test_detect_ai_generated_analysis_two_weak_markers() -> None:
    """Flag a body that accumulates at least two distinct weak markers."""
    body = "Based on the logs, it appears that the CCU connection is unstable. Root cause analysis points to a timeout."
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is True
    assert result["strong"] is False
    assert len(result["markers"]) >= 2


def test_detect_ai_generated_analysis_single_weak_marker_not_flagged() -> None:
    """Do not flag a body with only a single weak marker (avoid false positives)."""
    body = "It appears that the device stopped sending events after the update."
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is False


def test_detect_ai_generated_analysis_german_weak_markers() -> None:
    """Flag German AI prose using two distinct German weak markers."""
    body = (
        "Auf Grundlage der Logs ist die wahrscheinliche Ursache ein Funkproblem. "
        "Zusammenfassend sollte das Gerät neu angelernt werden."
    )
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is True


def test_format_ai_analysis_hint_emits_section_when_detected() -> None:
    """Render a redirect section in both languages when an AI analysis is detected."""
    detection = {"detected": True, "strong": True, "markers": ["as an ai"]}

    english = analyze_issue._format_ai_analysis_hint(detection, is_german=False)
    assert "AI-generated analysis" in english
    assert ".json" in english

    german = analyze_issue._format_ai_analysis_hint(detection, is_german=True)
    assert "KI-Analyse" in german
    assert ".json" in german


def test_format_ai_analysis_hint_empty_when_not_detected() -> None:
    """Render nothing when no AI analysis was detected."""
    detection = {"detected": False, "strong": False, "markers": []}
    assert analyze_issue._format_ai_analysis_hint(detection, is_german=False) == ""
    assert analyze_issue._format_ai_analysis_hint(detection, is_german=True) == ""


class _FakeLabel:
    """Minimal stand-in for a PyGithub label object."""

    def __init__(self, name: str) -> None:
        """Store the label name."""
        self.name = name


class _FakeRepo:
    """Minimal stand-in for a PyGithub repository, tracking created labels."""

    def __init__(self, *, existing_labels: set[str] | None = None) -> None:
        """Seed the repository with already-existing label names."""
        self._labels: set[str] = set(existing_labels or set())
        self.created: list[str] = []

    def create_label(self, *, name: str, color: str, description: str) -> _FakeLabel:
        """Record label creation and return the new label."""
        self._labels.add(name)
        self.created.append(name)
        return _FakeLabel(name)

    def get_label(self, name: str) -> _FakeLabel:
        """Return the label or raise the stubbed GithubException when absent."""
        if name in self._labels:
            return _FakeLabel(name)
        raise analyze_issue.GithubException(f"label '{name}' not found")


class _FakeIssue:
    """Minimal stand-in for a PyGithub issue, tracking label add/remove calls."""

    def __init__(self, *, labels: list[str] | None = None) -> None:
        """Seed the issue with already-applied label names."""
        self.labels: list[_FakeLabel] = [_FakeLabel(name) for name in (labels or [])]
        self.added: list[str] = []
        self.removed: list[str] = []

    def add_to_labels(self, *names: str) -> None:
        """Record the added labels."""
        self.added.extend(names)
        self.labels.extend(_FakeLabel(name) for name in names)

    def remove_from_labels(self, name: str) -> None:
        """Record and drop the removed label."""
        self.removed.append(name)
        self.labels = [label for label in self.labels if label.name != name]


def test_ensure_label_returns_true_when_present() -> None:
    """Do not create a label that already exists."""
    repo = _FakeRepo(existing_labels={"x"})
    assert analyze_issue.ensure_label(repo, "x", color="ffffff", description="d") is True
    assert repo.created == []


def test_ensure_label_creates_when_missing() -> None:
    """Create the label when it is missing from the repository."""
    repo = _FakeRepo()
    assert analyze_issue.ensure_label(repo, "x", color="ffffff", description="d") is True
    assert repo.created == ["x"]


def test_apply_needs_raw_data_label_adds_when_absent() -> None:
    """Add the triage label when it is not yet present on the issue."""
    repo = _FakeRepo(existing_labels={analyze_issue.NEEDS_RAW_DATA_LABEL})
    issue = _FakeIssue()
    analyze_issue.apply_needs_raw_data_label(issue, repo)
    assert analyze_issue.NEEDS_RAW_DATA_LABEL in issue.added


def test_apply_needs_raw_data_label_is_idempotent() -> None:
    """Do not re-add the triage label when it is already present."""
    repo = _FakeRepo(existing_labels={analyze_issue.NEEDS_RAW_DATA_LABEL})
    issue = _FakeIssue(labels=[analyze_issue.NEEDS_RAW_DATA_LABEL])
    analyze_issue.apply_needs_raw_data_label(issue, repo)
    assert issue.added == []


def test_apply_needs_raw_data_label_creates_missing_label() -> None:
    """Create the label on demand before applying it to the issue."""
    repo = _FakeRepo()
    issue = _FakeIssue()
    analyze_issue.apply_needs_raw_data_label(issue, repo)
    assert repo.created == [analyze_issue.NEEDS_RAW_DATA_LABEL]
    assert analyze_issue.NEEDS_RAW_DATA_LABEL in issue.added


def test_remove_needs_raw_data_label_when_present() -> None:
    """Remove the triage label once the required data has been provided."""
    issue = _FakeIssue(labels=[analyze_issue.NEEDS_RAW_DATA_LABEL])
    analyze_issue.remove_needs_raw_data_label(issue)
    assert issue.removed == [analyze_issue.NEEDS_RAW_DATA_LABEL]


def test_remove_needs_raw_data_label_noop_when_absent() -> None:
    """Do nothing when the triage label is not present on the issue."""
    issue = _FakeIssue()
    analyze_issue.remove_needs_raw_data_label(issue)
    assert issue.removed == []
