"""Tests for the GitHub issue-analyzer triage helpers."""

from __future__ import annotations

from collections.abc import Iterator
import importlib
import importlib.util
from pathlib import Path
import sys
import types

import pytest

_SCRIPT_PATH = Path(__file__).resolve().parents[2] / ".github" / "scripts" / "analyze_issue.py"


def _ensure_module(name: str, **attrs: object) -> None:
    """
    Make ``name`` importable, preferring the real package and stubbing only if absent.

    The analyzer script imports ``requests``, ``anthropic`` and ``github`` at module
    scope; the test environment does not install them, so a minimal stub is injected
    when the real package is unavailable (e.g. on CI).
    """
    if name in sys.modules:
        return
    try:
        importlib.import_module(name)
    except ModuleNotFoundError:
        stub = types.ModuleType(name)
        for attr, value in attrs.items():
            setattr(stub, attr, value)
        sys.modules[name] = stub


def _load_analyze_issue() -> types.ModuleType:
    """Load the standalone analyzer script with its heavy third-party deps stubbed out."""
    _ensure_module("requests", RequestException=type("RequestException", (Exception,), {}))
    _ensure_module("anthropic", Anthropic=object)
    _ensure_module(
        "github",
        Auth=object,
        Github=object,
        GithubException=type("GithubException", (Exception,), {}),
        Repository=object,
    )

    spec = importlib.util.spec_from_file_location("analyze_issue_under_test", _SCRIPT_PATH)
    if spec is None or spec.loader is None:
        pytest.fail(f"Could not load analyzer script from {_SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    # Register before exec so dataclass/typing machinery can resolve the module by name.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


analyze_issue = _load_analyze_issue()


@pytest.mark.parametrize(
    "body",
    [
        "Devices are unavailable after restart. Diagnostics and log attached.",
        "Nach dem Neustart sind die Geräte nicht erreichbar. Diagnose und Log sind angehängt.",
        "It crashes. Here is my log file: https://github.com/user-attachments/files/1/home-assistant.log",
        "",
    ],
)
def test_detect_ai_generated_analysis_clean_report(body: str) -> None:
    """Do not flag a normal report that contains no AI prose."""
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is False
    assert result["strong"] is False
    assert result["markers"] == []


@pytest.mark.parametrize(
    "body",
    [
        "As an AI language model, I analyzed your logs and found a connection issue.",
        "Als KI habe ich deine Logs analysiert und ein Verbindungsproblem gefunden.",
        "This was generated by a large language model based on the diagnostics.",
    ],
)
def test_detect_ai_generated_analysis_strong_marker(body: str) -> None:
    """Flag a single explicit self-identification marker as a strong detection."""
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is True
    assert result["strong"] is True
    assert result["markers"]


def test_detect_ai_generated_analysis_two_weak_markers() -> None:
    """Flag a body that accumulates at least two distinct weak markers."""
    body = "Based on the logs, it appears that the CCU connection is unstable. Root cause analysis points to a timeout."
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is True
    assert result["strong"] is False
    assert len(result["markers"]) >= 2


def test_detect_ai_generated_analysis_single_weak_marker_not_flagged() -> None:
    """Do not flag a body with only a single weak marker (avoid false positives)."""
    body = "It appears that the device stopped sending events after the update."
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is False


def test_detect_ai_generated_analysis_german_weak_markers() -> None:
    """Flag German AI prose using two distinct German weak markers."""
    body = (
        "Auf Grundlage der Logs ist die wahrscheinliche Ursache ein Funkproblem. "
        "Zusammenfassend sollte das Gerät neu angelernt werden."
    )
    result = analyze_issue.detect_ai_generated_analysis(body)
    assert result["detected"] is True


def test_format_ai_analysis_hint_emits_section_when_detected() -> None:
    """Render a redirect section in both languages when an AI analysis is detected."""
    detection = {"detected": True, "strong": True, "markers": ["as an ai"]}

    english = analyze_issue._format_ai_analysis_hint(detection, is_german=False)
    assert "AI-generated analysis" in english
    assert ".json" in english

    german = analyze_issue._format_ai_analysis_hint(detection, is_german=True)
    assert "KI-Analyse" in german
    assert ".json" in german


def test_format_ai_analysis_hint_empty_when_not_detected() -> None:
    """Render nothing when no AI analysis was detected."""
    detection = {"detected": False, "strong": False, "markers": []}
    assert analyze_issue._format_ai_analysis_hint(detection, is_german=False) == ""
    assert analyze_issue._format_ai_analysis_hint(detection, is_german=True) == ""


class _FakeLabel:
    """Minimal stand-in for a PyGithub label object."""

    def __init__(self, name: str) -> None:
        """Store the label name."""
        self.name = name


class _FakeRepo:
    """Minimal stand-in for a PyGithub repository, tracking created labels."""

    def __init__(self, *, existing_labels: set[str] | None = None) -> None:
        """Seed the repository with already-existing label names."""
        self._labels: set[str] = set(existing_labels or set())
        self.created: list[str] = []

    def create_label(self, *, name: str, color: str, description: str) -> _FakeLabel:
        """Record label creation and return the new label."""
        self._labels.add(name)
        self.created.append(name)
        return _FakeLabel(name)

    def get_label(self, name: str) -> _FakeLabel:
        """Return the label or raise the stubbed GithubException when absent."""
        if name in self._labels:
            return _FakeLabel(name)
        raise analyze_issue.GithubException(f"label '{name}' not found")


class _FakeIssue:
    """Minimal stand-in for a PyGithub issue, tracking label add/remove calls."""

    def __init__(self, *, labels: list[str] | None = None) -> None:
        """Seed the issue with already-applied label names."""
        self.labels: list[_FakeLabel] = [_FakeLabel(name) for name in (labels or [])]
        self.added: list[str] = []
        self.removed: list[str] = []

    def add_to_labels(self, *names: str) -> None:
        """Record the added labels."""
        self.added.extend(names)
        self.labels.extend(_FakeLabel(name) for name in names)

    def remove_from_labels(self, name: str) -> None:
        """Record and drop the removed label."""
        self.removed.append(name)
        self.labels = [label for label in self.labels if label.name != name]


def test_ensure_label_returns_true_when_present() -> None:
    """Do not create a label that already exists."""
    repo = _FakeRepo(existing_labels={"x"})
    assert analyze_issue.ensure_label(repo, "x", color="ffffff", description="d") is True
    assert repo.created == []


def test_ensure_label_creates_when_missing() -> None:
    """Create the label when it is missing from the repository."""
    repo = _FakeRepo()
    assert analyze_issue.ensure_label(repo, "x", color="ffffff", description="d") is True
    assert repo.created == ["x"]


def test_apply_needs_raw_data_label_adds_when_absent() -> None:
    """Add the triage label when it is not yet present on the issue."""
    repo = _FakeRepo(existing_labels={analyze_issue.NEEDS_RAW_DATA_LABEL})
    issue = _FakeIssue()
    analyze_issue.apply_needs_raw_data_label(issue, repo)
    assert analyze_issue.NEEDS_RAW_DATA_LABEL in issue.added


def test_apply_needs_raw_data_label_is_idempotent() -> None:
    """Do not re-add the triage label when it is already present."""
    repo = _FakeRepo(existing_labels={analyze_issue.NEEDS_RAW_DATA_LABEL})
    issue = _FakeIssue(labels=[analyze_issue.NEEDS_RAW_DATA_LABEL])
    analyze_issue.apply_needs_raw_data_label(issue, repo)
    assert issue.added == []


def test_apply_needs_raw_data_label_creates_missing_label() -> None:
    """Create the label on demand before applying it to the issue."""
    repo = _FakeRepo()
    issue = _FakeIssue()
    analyze_issue.apply_needs_raw_data_label(issue, repo)
    assert repo.created == [analyze_issue.NEEDS_RAW_DATA_LABEL]
    assert analyze_issue.NEEDS_RAW_DATA_LABEL in issue.added


def test_remove_needs_raw_data_label_when_present() -> None:
    """Remove the triage label once the required data has been provided."""
    issue = _FakeIssue(labels=[analyze_issue.NEEDS_RAW_DATA_LABEL])
    analyze_issue.remove_needs_raw_data_label(issue)
    assert issue.removed == [analyze_issue.NEEDS_RAW_DATA_LABEL]


def test_remove_needs_raw_data_label_noop_when_absent() -> None:
    """Do nothing when the triage label is not present on the issue."""
    issue = _FakeIssue()
    analyze_issue.remove_needs_raw_data_label(issue)
    assert issue.removed == []


# ---------------------------------------------------------------------------
# Issue-form parsing
# ---------------------------------------------------------------------------

_EN_FORM_BODY = """### The problem

The light entity is missing after the update.

### What version of Homematic(IP) Local for OpenCCU has the issue?

2.8.3

### What was the last working version of Homematic(IP) Local for OpenCCU?

_No response_

### What type of installation are you running?

Home Assistant OS
"""

_DE_FORM_BODY = """### Das Problem

Nach dem Update fehlt die Entität.

### Bei welcher Version von HomematicIP (lokal) tritt das Problem auf?

2.8.1

### Welche war die letzte funktionierende Version von Homematic(IP) Local for OpenCCU?

2.7.3
"""


def test_parse_form_fields_english_template() -> None:
    """Parse labels and values from an English issue-form body."""
    fields = analyze_issue.parse_form_fields(_EN_FORM_BODY)
    assert fields["What version of Homematic(IP) Local for OpenCCU has the issue?"] == "2.8.3"
    assert fields["What type of installation are you running?"] == "Home Assistant OS"


def test_parse_form_fields_normalizes_no_response() -> None:
    """Normalize the GitHub placeholder for empty fields to an empty string."""
    fields = analyze_issue.parse_form_fields(_EN_FORM_BODY)
    assert fields["What was the last working version of Homematic(IP) Local for OpenCCU?"] == ""


def test_parse_form_fields_empty_body() -> None:
    """Return an empty mapping for an empty or template-free body."""
    assert analyze_issue.parse_form_fields("") == {}
    assert analyze_issue.parse_form_fields("just some free text") == {}


def test_get_form_field_version_english() -> None:
    """Find the integration-version field in the English template."""
    fields = analyze_issue.parse_form_fields(_EN_FORM_BODY)
    value = analyze_issue.get_form_field(fields, markers=analyze_issue.VERSION_FIELD_MARKERS)
    assert value == "2.8.3"


def test_get_form_field_version_german_does_not_match_last_working() -> None:
    """Find the German version field and never the "last working version" field."""
    fields = analyze_issue.parse_form_fields(_DE_FORM_BODY)
    value = analyze_issue.get_form_field(fields, markers=analyze_issue.VERSION_FIELD_MARKERS)
    assert value == "2.8.1"


def test_get_form_field_missing() -> None:
    """Return None when the field does not exist at all."""
    assert analyze_issue.get_form_field({}, markers=analyze_issue.VERSION_FIELD_MARKERS) is None


# ---------------------------------------------------------------------------
# Deterministic version check
# ---------------------------------------------------------------------------

_RELEASES = analyze_issue.ReleaseInfo(
    stable="2.8.3",
    prerelease="2.9.0b1",
    all_versions=frozenset({"2.8.3", "2.8.2", "2.8.1", "2.9.0b1", "2.0.0"}),
)


def test_check_reported_version_ok() -> None:
    """Accept the current stable version."""
    check = analyze_issue.check_reported_version("2.8.3", releases=_RELEASES)
    assert check.status == "ok"


def test_check_reported_version_ok_prerelease() -> None:
    """Accept a newer pre-release without flagging it."""
    check = analyze_issue.check_reported_version("2.9.0b1", releases=_RELEASES)
    assert check.status == "ok"


def test_check_reported_version_outdated() -> None:
    """Flag a known but outdated release."""
    check = analyze_issue.check_reported_version("2.8.1", releases=_RELEASES)
    assert check.status == "outdated"
    assert check.stable == "2.8.3"


def test_check_reported_version_unknown() -> None:
    """Flag a version that matches no published release (e.g. HA or CCU version)."""
    for reported in ("2026.7.2", "3.79.6", "core-2026.7.2"):
        check = analyze_issue.check_reported_version(reported, releases=_RELEASES)
        assert check.status == "unknown", reported


def test_check_reported_version_prefix_tolerance() -> None:
    """Accept a shortened version like "2.8" when a matching release exists."""
    check = analyze_issue.check_reported_version("2.8", releases=_RELEASES)
    assert check.status == "ok"


def test_check_reported_version_strips_v_prefix() -> None:
    """Normalize a leading "v" before comparing against the release set."""
    check = analyze_issue.check_reported_version("v2.8.3", releases=_RELEASES)
    assert check.status == "ok"


def test_check_reported_version_missing() -> None:
    """Report a missing version for empty or absent field values."""
    assert analyze_issue.check_reported_version(None, releases=_RELEASES).status == "missing"
    assert analyze_issue.check_reported_version("  ", releases=_RELEASES).status == "missing"


def test_check_reported_version_no_data() -> None:
    """Make no validity statement when the release list could not be fetched."""
    empty = analyze_issue.ReleaseInfo()
    check = analyze_issue.check_reported_version("9.9.9", releases=empty)
    assert check.status == "no_data"


# ---------------------------------------------------------------------------
# Attachment / screenshot detection
# ---------------------------------------------------------------------------


def test_detect_attachments_urls() -> None:
    """Detect diagnostics and log attachments from uploaded file URLs."""
    body = (
        "Diagnostics: https://github.com/user-attachments/files/1/config_entry-diagnostics.json\n"
        "Log: https://github.com/user-attachments/files/2/home-assistant.log"
    )
    has_diagnostics, has_logs = analyze_issue.detect_attachments(body)
    assert has_diagnostics is True
    assert has_logs is True


def test_detect_attachments_inline_log_counts_as_log() -> None:
    """Count a fenced code block full of log lines as provided log data."""
    log_lines = "\n".join(f"2026-07-18 12:00:0{i} ERROR (MainThread) something failed" for i in range(6))
    body = f"It fails:\n```\n{log_lines}\n```"
    has_diagnostics, has_logs = analyze_issue.detect_attachments(body)
    assert has_diagnostics is False
    assert has_logs is True


def test_detect_attachments_short_code_block_is_not_a_log() -> None:
    """Do not count a short code snippet as log data."""
    body = "```\nyaml: value\n```"
    _, has_logs = analyze_issue.detect_attachments(body)
    assert has_logs is False


def test_detect_screenshots() -> None:
    """Detect screenshots via asset URLs and markdown images."""
    assert analyze_issue.detect_screenshots("![img](https://github.com/user-attachments/assets/abc)") is True
    assert analyze_issue.detect_screenshots("see https://example.com/foo.png") is True
    assert analyze_issue.detect_screenshots("no images here") is False


# ---------------------------------------------------------------------------
# Device-model extraction
# ---------------------------------------------------------------------------


def test_extract_device_model() -> None:
    """Extract the first device-model designation from text."""
    assert analyze_issue.extract_device_model("HmIP-eTRV-2 fehlender window_state") == "HmIP-eTRV-2"
    assert analyze_issue.extract_device_model("HM-PB-2-WM55 funktioniert nicht") == "HM-PB-2-WM55"
    assert analyze_issue.extract_device_model("no device mentioned") is None


def test_extract_device_model_skips_interface_names() -> None:
    """Skip interface designations that are useless as duplicate-search terms."""
    assert analyze_issue.extract_device_model("HmIP-RF disconnects, HmIP-SWDO-2 affected") == "HmIP-SWDO-2"


# ---------------------------------------------------------------------------
# Similar-issue search (search API, not recently-updated listing)
# ---------------------------------------------------------------------------


class _FakeSearchResultIssue:
    """Minimal stand-in for a PyGithub issue returned by the search API."""

    def __init__(self, number: int, title: str = "title", state: str = "open") -> None:
        """Store the search-result fields."""
        self.number = number
        self.title = title
        self.html_url = f"https://github.com/x/y/issues/{number}"
        self.state = state


class _FakePaginatedList:
    """
    Mimic PyGithub's ``PaginatedList`` slice semantics (v2.9.1).

    Slicing returns a lazy view that probes ``list[index]`` while the list
    "could grow" (i.e. before the first page was fetched). On an empty result
    set the first probe fetches nothing and raises ``IndexError`` — the crash
    observed in the live analyzer run for issue #3300.
    """

    def __init__(self, elements: list[_FakeSearchResultIssue]) -> None:
        """Store the canned elements; nothing is 'fetched' yet."""
        self._elements = elements
        self._fetched = False

    def __getitem__(self, index: int | slice) -> _FakeSearchResultIssue | _FakePaginatedList._Slice:
        """Return one element (fetching first) or a lazy slice view."""
        if isinstance(index, slice):
            return self._Slice(self, index)
        self._fetched = True
        return self._elements[index]

    def __iter__(self) -> Iterator[_FakeSearchResultIssue]:
        """Iterate all elements; safe on empty result sets."""
        self._fetched = True
        yield from self._elements

    def _is_bigger_than(self, index: int) -> bool:
        return len(self._elements) > index or not self._fetched

    class _Slice:
        """Lazy slice view over the paginated list, as in PyGithub."""

        def __init__(self, paginated_list: _FakePaginatedList, the_slice: slice) -> None:
            """Store list and slice bounds."""
            self._list = paginated_list
            self._start = the_slice.start or 0
            self._stop = the_slice.stop
            self._step = the_slice.step or 1

        def __iter__(self) -> Iterator[_FakeSearchResultIssue]:
            """Yield elements by probing the underlying list per index."""
            index = self._start
            while self._stop is None or index < self._stop:
                if self._list._is_bigger_than(index):
                    yield self._list[index]  # type: ignore[misc]
                    index += self._step
                else:
                    return


class _FakeGithub:
    """Minimal stand-in for a PyGithub client capturing search queries."""

    def __init__(self, results: list[_FakeSearchResultIssue]) -> None:
        """Store the canned search results."""
        self._results = results
        self.queries: list[str] = []

    def search_issues(self, query: str) -> _FakePaginatedList:
        """Record the query and return the canned results as a paginated list."""
        self.queries.append(query)
        return _FakePaginatedList(self._results)


def test_search_similar_issues_uses_search_api_with_term() -> None:
    """Pass the search term to the search API query."""
    gh = _FakeGithub([_FakeSearchResultIssue(11), _FakeSearchResultIssue(12)])
    items = analyze_issue.search_similar_issues(
        gh,  # type: ignore[arg-type]
        repo_full_name="SukramJ/aiohomematic",
        search_terms=["HmIP-eTRV-2"],
        current_issue_number=99,
    )
    assert gh.queries == ["repo:SukramJ/aiohomematic is:issue HmIP-eTRV-2"]
    assert [item["number"] for item in items] == [11, 12]


def test_search_similar_issues_excludes_current_and_dedupes() -> None:
    """Exclude the current issue and deduplicate results across terms."""
    gh = _FakeGithub([_FakeSearchResultIssue(99), _FakeSearchResultIssue(11), _FakeSearchResultIssue(11)])
    items = analyze_issue.search_similar_issues(
        gh,  # type: ignore[arg-type]
        repo_full_name="SukramJ/aiohomematic",
        search_terms=["term-a", "term-b"],
        current_issue_number=99,
    )
    assert [item["number"] for item in items] == [11]


def test_search_similar_issues_sanitizes_query_syntax() -> None:
    """Strip search-syntax characters from terms so they cannot break the query."""
    gh = _FakeGithub([])
    analyze_issue.search_similar_issues(
        gh,  # type: ignore[arg-type]
        repo_full_name="SukramJ/aiohomematic",
        search_terms=['error: "Parameter not found"'],
        current_issue_number=1,
    )
    assert gh.queries == ["repo:SukramJ/aiohomematic is:issue error   Parameter not found"]


def test_search_similar_issues_empty_search_results_do_not_crash() -> None:
    """Return no items instead of raising when a term yields zero search hits."""
    gh = _FakeGithub([])
    items = analyze_issue.search_similar_issues(
        gh,  # type: ignore[arg-type]
        repo_full_name="SukramJ/aiohomematic",
        search_terms=["doorbell ring event"],
        current_issue_number=3300,
    )
    assert items == []


# ---------------------------------------------------------------------------
# Comment formatting (triage only - no diagnosis sections, no critical banners)
# ---------------------------------------------------------------------------


def _make_triage(**overrides: object) -> object:
    """Build a TriageResult with sensible defaults for formatting tests."""
    defaults: dict[str, object] = {
        "language": "de",
        "summary": "Entität fehlt nach Update.",
        "version_check": analyze_issue.VersionCheck(status="ok", reported="2.8.3", stable="2.8.3"),
        "has_diagnostics": True,
        "has_logs": True,
        "ai_detection": {"detected": False, "strong": False, "markers": []},
        "is_feature_request": False,
        "is_device_related": False,
        "has_screenshots": False,
        "suggested_docs": [],
        "similar_items": [],
    }
    defaults.update(overrides)
    return analyze_issue.TriageResult(**defaults)  # type: ignore[arg-type]


def test_format_comment_contains_no_diagnosis_sections() -> None:
    """Never render diagnosis sections or critical banners."""
    triage = _make_triage(
        version_check=analyze_issue.VersionCheck(status="unknown", reported="3.79.6", stable="2.8.3"),
        has_diagnostics=False,
        has_logs=False,
    )
    comment = analyze_issue.format_comment(triage)
    assert "KRITISCH" not in comment
    assert "CRITICAL" not in comment
    assert "Analyse der angehängten Daten" not in comment
    assert "Attachment Analysis" not in comment


def test_format_comment_version_notice_outdated_is_neutral() -> None:
    """Render a neutral update hint for a known but outdated version."""
    triage = _make_triage(
        version_check=analyze_issue.VersionCheck(status="outdated", reported="2.8.1", stable="2.8.3"),
    )
    comment = analyze_issue.format_comment(triage)  # type: ignore[arg-type]
    assert "Versionshinweis" in comment
    assert "2.8.1" in comment
    assert "2.8.3" in comment
    assert "🚨" not in comment


def test_format_comment_version_notice_absent_when_ok_or_no_data() -> None:
    """Render no version notice when the version is fine or no release data exists."""
    for status in ("ok", "no_data"):
        triage = _make_triage(version_check=analyze_issue.VersionCheck(status=status, reported="x", stable="2.8.3"))
        comment = analyze_issue.format_comment(triage)  # type: ignore[arg-type]
        assert "Versionshinweis" not in comment


def test_format_comment_missing_info_lists_version_field() -> None:
    """List an empty version field in the missing-information section."""
    triage = _make_triage(
        version_check=analyze_issue.VersionCheck(status="missing", stable="2.8.3"),
        has_diagnostics=False,
        has_logs=True,
    )
    comment = analyze_issue.format_comment(triage)  # type: ignore[arg-type]
    assert "Fehlende Pflichtinformationen" in comment
    assert "Integrationsdiagnose" in comment
    assert "Version der Integration" in comment
    assert "❌ **Protokolldatei**" not in comment


def test_format_comment_feature_request_hint() -> None:
    """Point feature requests to the discussions."""
    triage = _make_triage(is_feature_request=True)
    comment = analyze_issue.format_comment(triage)  # type: ignore[arg-type]
    assert "Feature-Wunsch" in comment
    assert "Diskussionen" in comment


def test_format_comment_header_is_stable_for_duplicate_detection() -> None:
    """Keep the header text that has_bot_comment relies on."""
    de_comment = analyze_issue.format_comment(_make_triage())  # type: ignore[arg-type]
    en_comment = analyze_issue.format_comment(_make_triage(language="en"))  # type: ignore[arg-type]
    assert "Automatische Issue-Analyse" in de_comment
    assert "Automatic Issue Analysis" in en_comment


def test_format_comment_limits_suggested_docs_to_two() -> None:
    """Render at most two documentation links and drop unknown doc keys."""
    triage = _make_triage(
        suggested_docs=[
            {"doc_key": "troubleshooting", "reason": "r1"},
            {"doc_key": "unignore", "reason": "r2"},
            {"doc_key": "glossary", "reason": "r3"},
            {"doc_key": "nonexistent", "reason": "r4"},
        ],
    )
    comment = analyze_issue.format_comment(triage)  # type: ignore[arg-type]
    assert "troubleshooting" in comment
    assert "unignore" in comment
    assert "glossary" not in comment.split("Hilfreiche Dokumentation")[1]
    assert "nonexistent" not in comment
