# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2026
"""
Regenerate the vendored openccu-loom wire-enum snapshot.

The drift guard in ``test_loom_wire_enum_drift_contract.py`` compares
aiohomematic's ``DataPointCategory`` / ``DataPointType`` enums against a
vendored copy of the daemon's published wire catalogue
(``openccu-loom/assets/schemas/enums.json``).

aiohomematic deliberately takes no dependency on the openccu-loom
ecosystem, so the catalogue is vendored as ``loom_wire_enums.json``
rather than imported. Run this script to refresh that snapshot whenever
the daemon's wire contract changes:

    python3 tests/contract/refresh_loom_wire_enums.py [path-to-enums.json]

With no argument it looks for the daemon repo as a sibling checkout
(``../openccu-loom/assets/schemas/enums.json``). Refreshing the snapshot
is a deliberate, reviewable act: a diff here means the wire contract
moved and aiohomematic's enums must move with it (or the change is a
breaking one that needs coordination).
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

_HERE = Path(__file__).resolve().parent
_FIXTURE = _HERE / "loom_wire_enums.json"
_DEFAULT_SOURCE = _HERE.parents[2] / "openccu-loom" / "assets" / "schemas" / "enums.json"
_ENUMS = ("DataPointCategory", "DataPointType")


def _enum_values(catalogue: object, name: str) -> list[str]:
    """
    Extract the sorted ``wire_value`` list for one enum.

    ``enums`` is a list of ``{"name", "values": [{"wire_value", ...}]}``
    objects (it has also shipped as a name-keyed dict; handle both).
    """
    entry = catalogue[name] if isinstance(catalogue, dict) else next(e for e in catalogue if e.get("name") == name)
    return sorted(v["wire_value"] for v in entry["values"])


def main() -> int:
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT_SOURCE
    if not source.is_file():
        sys.stderr.write(
            f"enums.json not found at {source}\n"
            "Pass the path explicitly: "
            "python3 tests/contract/refresh_loom_wire_enums.py <enums.json>\n"
        )
        return 1

    catalogue = json.loads(source.read_text())["enums"]
    snapshot = {
        "_provenance": {
            "source": "openccu-loom/assets/schemas/enums.json (enums[].name == DataPointCategory|DataPointType)",
            "generator": "generated by openccu-loom-types from the daemon's pkg/hmenum",
            "note": "Vendored snapshot of the daemon wire enum catalogue for the "
            "drop-in drift guard. Do NOT hand-edit; regenerate with the command below.",
            "refresh": "python3 tests/contract/refresh_loom_wire_enums.py",
        },
        **{name: _enum_values(catalogue, name) for name in _ENUMS},
    }
    _FIXTURE.write_text(json.dumps(snapshot, indent=2) + "\n")
    sys.stdout.write(f"wrote {_FIXTURE.relative_to(_HERE.parents[1])}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
